name: Fix Styling Issues

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install PHP-CS-Fixer
        run: composer global require friendsofphp/php-cs-fixer
      - name: Add Composer global bin directory to PATH
        run: |
          echo "$env:PATH;C:\Users\runneradmin\AppData\Roaming\Composer\vendor\bin" | Out-File -Encoding ASCII -FilePath "$env:USERPROFILE\.profile"
      - name: List files in the directory
        run: dir
      - name: Verify PHP-CS-Fixer Installation
        run: php -r "echo shell_exec('composer global exec which php-cs-fixer');"
      - name: Run PHP-CS-Fixer
        run: php C:\Users\runneradmin\AppData\Roaming\Composer\vendor\bin\php-cs-fixer fix --config .php-cs-fixer.php
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling issues (PHP-CS-Fixer)
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
