name: Fix Styling Issues

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for PHP-CS-Fixer image
        run: |
          docker pull ghcr.io/php-cs-fixer/php-cs-fixer:${{ env.FIXER_VERSION }}-php${{ env.PHP_VERSION }}
      - name: PHP-CS-Fixer
        env:
          FIXER_VERSION: 3.64.0
          PHP_VERSION: 8.3
        run: |
          docker run --rm \
            -v $(pwd):/code \
            ghcr.io/php-cs-fixer/php-cs-fixer:${FIXER_VERSION}-php${PHP_VERSION} \
            fix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling issues (PHP-CS-Fixer)
