name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-phpunit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: sail
      DB_PASSWORD: password

    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_DATABASE: mysql
            MYSQL_USER: mysql
            MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: pcov

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare Application
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan storage:link
          timeout 60s bash -c 'until mysqladmin ping -h"127.0.0.1" --silent; do sleep 1; done'
          php artisan migrate --seed

      - name: PHPUnit
        run: php artisan test --parallel --coverage-clover=coverage.xml --passthru-php="'-d' 'pcov.enabled=1' '-d' 'pcov.directory=.' '-d' 'pcov.exclude=~vendor~'"
      - uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
